DROP TABLE IF exists workspaces;
CREATE TABLE workspaces (
  id INT(11) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
  team_id VARCHAR(30) NOT NULL,
  team_name VARCHAR(255) NOT NULL,
  access_token VARCHAR(255) NOT NULL,
  authorizing_user_id VARCHAR(30) NOT NULL,
  app_home VARCHAR(30) NOT NULL,
  creation_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  update_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);
